name: Build and Distribute APK to Firebase

on:
  push:
    branches:
      - main  # Ana branch'e push yapıldığında tetiklenir
  pull_request:
    types: [closed]
    branches:
      - main  # Ana branch'e yapılan pull request (merge) işlemlerini tetikler

jobs:
  build:
    name: Build APK and Distribute to Firebase
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java, Android SDK vs. Gerekli Ortamı Kur
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'  # JDK dağıtımını belirtiyoruz

      # 3. Keystore'u Çöz
      - name: Decode keystore
        env:
          DATA: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p app/key  # app/key dizinini oluştur
          echo $DATA | base64 -di > app/key/BetanStockApp.jks

      # 4. Google Services JSON Dosyasını Yarat
      - name: Create google-services.json
        env:
          DATA: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      # 5. Gradle Bağımlılıklarını Yükle
      - name: Install Dependencies
        run: ./gradlew build

      # 6. APK'yı İmzala
      - name: Build APK
        run: ./gradlew assembleRelease  # Release APK oluşturur

      # 7. Firebase CLI'ı Kur
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      # 8. Firebase CLI versiyonunu kontrol et
      - name: Check Firebase CLI version
        run: firebase --version

      # 9. APK'nın var olup olmadığını kontrol et
      - name: Check if APK exists
        run: ls -l ./app/build/outputs/apk/release/

      # 10. Firebase App Distribution'a APK'yı Yükle
      - name: Upload APK to Firebase
        run: firebase appdistribution:distribute ./app/build/outputs/apk/release/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups "testers" \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --debug
